name: slack-alert-failure

on:
  workflow_run:
    workflows:
      - "Orange Barbossa Refresh"
    types:
      - completed

jobs:
  notify-slack:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification (fail)
        run: |
          echo ${{ github.event.workflow_run.conclusion == 'failure' }}
          echo ${{ github.event.pull_request.base.ref }}
          if [[ "${{ github.event.pull_request.base.ref }}" == "develop" ]]; then
            CHANNEL="${{ secrets.GA_SLACK_WEBHOOK_DEV }}"
          elif [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            CHANNEL="${{ secrets.GA_SLACK_WEBHOOK_PROD }}"
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\":warning: Build failed on commit to branch '${{ github.event.workflow_run.head_branch }}' in the '${{ github.repository }}' repo.\
            Check the details here: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'\"}" \
            $CHANNEL
